### ISSUE TITLE
How to define functions in a configuration file and pass specific arguments to these functions when loading the configuration file?

### ISSUE THREAD

**Issue by yangmiao7** [unjs/c12#121]
### Describe the feature

How to define functions in a configuration file and pass specific arguments to these functions when loading the configuration file?

**Comment by pi0** [comment]
Sorry for late reply. I'm not sure if it is easily possible for generic onfig loader. Also making config to depend on args makes it less predictable as a static config to rely on.

I would recommend using environment variables and dotenv for implicit arg passing.

**Comment by eaton** [comment]
I’ve been chewing on this as well, for a utility that supports “basic” configuration in JSON/YAML/etc, or “advanced” configuration in js/ts files.

One option would be to add a “config context” property to the loader options; any value or object in there would be passed to configuration functions as a parameter. They would still be expected to return their configuration, but advanced config scenarios would be a lot easier to handle…

**Comment by pi0** [comment]
@eaton feel free to open a new issue with some code snippets if you feel it is still valuable addition.
