### ISSUE TITLE
Support reverse merge keys

### ISSUE THREAD

**Issue by pi0** [unjs/c12#138]
Allow some arrays to be merged in reverse orders when the option is supposed to be bottom-up sorted. (like `nuxt.modules[]`) with an option like `reverseArrays: ['modules']`

**Comment by cpreston321** [comment]
@pi0 What about deep arrays within the config? Would it be `dotNotation` like `['modules', 'newObj.newArr']` ? 

I wrote up some code but wanted your input: 

```ts
  // Reverse arrays if defined
  if (options.reverseArrays && Array.isArray(options.reverseArrays)) {
    for (const key of options.reverseArrays) {
      const path = key
        .split(".")
        .map((p) => `['${p}']`)
        .join("");

      // eslint-disable-next-line no-eval
      const tempArr = eval(`r.config${path}`); // Need to use eval to support nested paths

      if (tempArr && Array.isArray(tempArr)) {
        r.config[key] = r.config[key].reverse();
      }
    }
```

**Comment by pi0** [comment]
~> https://github.com/unjs/c12/issues/145
