### ISSUE TITLE
key merge strategy

### ISSUE THREAD

**Issue by pi0** [unjs/c12#145]
(this is a primary draft to explain the idea)

Related: #138, #87 

Sometime default `defu` merging strategy is not ideal. We could allow a custom defu merger but it is not initiative. 

I was thinking to try with an object syntax like this:

```js
{
  mergeStrategy: {
    modules: (a, b) => a.concat(b)
  }
}
```

(it could be backported to defu)

**Comment by cpreston321** [comment]
So you are thinking if mergeStrategy is defined in the user config vs the c12 config?

**Comment by pi0** [comment]
c12 config (controlled by `nuxt` for example`). Yes we need a `defuFn` wrapper to use consistently every place in c12, that extends `defuArray`-like behavior and allows overriding behavior per-key with simple object. So for example nuxt can do reverse merge on `modules` array.

**Comment by cpreston321** [comment]
I'll try to implement this and give it a shot 💯 Thanks for the feedback

**Comment by pi0** [comment]
Implemented as simpler merger function so that end-users have full control https://github.com/unjs/c12/pull/160
