### ISSUE TITLE
Allow disabling extending from remote sources with giget.

### ISSUE THREAD

**Issue by web-dev-sam** [unjs/c12#180]
### Describe the feature

I want to make it possible to simply extend from local files, however I don't want to support remote config extending from github, gitlab or alike. I currently dont see a way how this is done. A simple config option to disable remote extending would be really helpful and shouldn't be too hard to do.

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Makes sense. PR welcome 👍🏼
