### ISSUE TITLE
Incorrect config file updated using the `updateConfig` function when `cwd` is missing a trailing slash

### ISSUE THREAD

**Issue by abhi12299** [unjs/c12#187]
### Environment

Node: `v20.8.1`
c12: `2.0.0-beta.1`

### Reproduction

This issue was identified in the nuxt repo: https://github.com/nuxt/nuxt/pull/28797

Link to reproduce the issue: https://stackblitz.com/edit/stackblitz-starters-ea59nb?file=README.md

### Describe the bug

Without a trailing slash at the end of `cwd`, the `updateConfig` ends up modifying the wrong file.

**Comment by pi0** [comment]
Thanks for nice report. fixed in latest 1.x (and v2 beta)

**Comment by n0099** [comment]
5b0c89ca1d16a8ee5b043d905135a9e81bc5c842
