### ISSUE TITLE
Support loading config from `package.json`

### ISSUE THREAD

**Issue by ontoneio** [unjs/c12#29]
I am just curious, because it doesn't look like it from the looks of things, but wanted to be sure. 
It would be great to be able to do this and replace other config packages like `find-config` in my case.

This library supports loading from a `"config"` key in `package.json` and I am noticing several others do as well.

Be nice to be able to parse those out in addtion.

**Comment by pi0** [comment]
Hi. Not at the latest feature but we could support 👍🏼

**Comment by fullstackjedi** [comment]
This is definitely something I would love to see here. Any plans to add it? Are PR's welcomed?

**Comment by pi0** [comment]
Surely PR welcome! We can use `readPackageJSON` from [pkg-types](https://github.com/unjs/pkg-types) to load closest package.json as source.

**Comment by NozomuIkuta** [comment]
Let me close this issue, because it has been already resolved by #52 (GitHub magic comment was not used in PR message for auto-closing).
