### ISSUE TITLE
Support private git repos via personal access tokens

### ISSUE THREAD

**Issue by manniL** [unjs/c12#50]
Hey!

It'd be amazing if we could support private GitHub/GitLab/BitBucket repos too, maybe by utilizing Personal Access Tokens?

**Comment by pi0** [comment]
Have you tried `GIGET_AUTH` environment vatiable? It allows setting token for providers.

**Comment by pi0** [comment]
Supported via https://github.com/unjs/c12/commit/4c7590ab94c667acd45fb1df05026d49b89431bc
