### ISSUE TITLE
Cannot extends from a directory that contains a dot

### ISSUE THREAD

**Issue by stafyniaksacha** [unjs/c12#71]
### Environment

- Nuxt 3.3.2

### Reproduction

```
.some-layer/
another-layer.v2/
nuxt.config.ts
```

With `nuxt.config.ts`
```ts
export default defineNuxtConfig({
  extends: ['./.some-layer', './another-layer.v2'],
})
```

### Describe the bug

having a `.` in directory name result in unwanted behavior due to usage of `extname`

https://github.com/unjs/c12/blob/47d8ca87c960c660cd35c9e67851180cb4837d0e/src/loader.ts#L258

maybe using `fs.stat().isDirectory()` would fix it?

**Comment by pi0** [comment]
Hi. Sorry for getting to this late. Checking fs stat is probably best however for now i have used another workaround to make sure dot is not in the first in last segment. (https://github.com/unjs/c12/commit/4adcbbe1527f720d4e21a281e63dfa259f38e0d1#diff-0a1342822ff2e711a79fd7036fdc352146751bd42d7d5845a2938f903723f74bR259)
