### ISSUE TITLE
dotenv maybe not work?

### ISSUE THREAD

**Issue by gumingWu** [unjs/c12#86]
### Environment

node v18.14.2

### Reproduction

none

### Describe the bug

I found that although I set the `dotenv` to true, it's not worked

and then I saw the code, it's lost to merge the dotenv config?

![image](https://github.com/unjs/c12/assets/24989299/18907aa8-b05d-4403-9f35-aeecfb5f8b64)

**Comment by pi0** [comment]
Hi. Loading dotenv causes them to be loaded into `process.env`. 

Can you please provide a reproduction? 🙏🏼

**Comment by gumingWu** [comment]
> Hi. Loading dotenv causes them to be loaded into `process.env`.
> 
> Can you please provide a reproduction? 🙏🏼

Thanks for your reply very much, I finally found the `.env` config in `process.env`  ^o^

Maybe it would be better to mark it in the docs~

**Comment by maou-shonen** [comment]
> Hi. Loading dotenv causes them to be loaded into `process.env`.
> 
> Can you please provide a reproduction? 🙏🏼
Is it expected that dotenv only loads into process.env? I noticed that when I use it, it doesn't seem to override the config, which is a bit confusing to me.

I also checked the unit tests, and it appears that dotenv is not correctly validated there as well.
