### ISSUE TITLE
Array merge order for extends is unintuitive

### ISSUE THREAD

**Issue by dword-design** [unjs/c12#87]
### Environment

Node.js: v18.12.1
c12: 1.4.1

### Reproduction

https://github.com/dword-design/demo-c12-array-merge

### Describe the bug

1. Create a config with a plugins property `plugins: ['local 1', 'local 2']`
2. Create a parent config `parent.js` with plugins property `plugins: ['inherited 1', 'inherited 2']`
3. Reference the parent in the config using `extends: './parent.js'`

Expected: The resulting config contains `plugins: ['inherited 1', 'inherited 2', 'local 1', 'local 2']`.
Actual: The resulting config contains `plugins: ['local 1', 'local 2', 'inherited 1', 'inherited 2']`.

I would expect the order in the array to always be parent first and then child. Has direct implications if you have a plugin or module system where the order is important. Actually it is an issue in [Nuxt](https://www.npmjs.com/package/nuxt) and this seems to be the root cause.

### Additional context

See also https://github.com/unjs/defu/issues/98

**Comment by pi0** [comment]
Hi dear @dword-design thanks for spending time on making proper reproduction and explanation and sorry for late reply.

I respect that it might not be of your preference but it is the convention we have set aceoss (wide) ecosystem of unjs and nitro that arrays are sorted from high level to low level (defaults) so it is unlikely to be changed.

Still if you strongly belive, a usage outside of nuxt, might benefit from reversed order, PR is welcome to support it via an option + custom defu merger.

**Comment by pi0** [comment]
Reopening this to consider supporting an opt in easy option for merge strategy.
