### ISSUE TITLE
optionally remove `$env` and other internal keys from resolved configuration

### ISSUE THREAD

**Issue by LoTwT** [unjs/c12#99]
## current

``` ts
// temp.config.ts
export default {
  a: 1,

  $env: {
    dev: {
      a: "Dev"
    }
  }
}

// index.ts
const { config } = await loadConfig({
  name: "temp",
})
```

The resolved config above is `{ a: 1, '$env': { dev: { a: 'Dev' } } }`.

When the user deconstructs the resolved config into another object, environment-specific fields are unnecessary.

## alternative proposal

- Ignore environment-specific fields in the resolved config
   - or maybe add a flag for users to choose
- Add another field, such as `resolvedConfig`, it only has the fields which are user input

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi. We preserve the source config by default so that if you need to have a custom logic to check the precise source of a (merged) configuration is from config, env or layers, you can.

However it makes sense to have an option to opt-out and remove built-in `$` keys
